---

- include: package.yml

- include: test.yml
  when: sphinx_test

- include: config.yml

- name: Be sure sphinxsearch is running and enabled
  service: name=sphinxsearch state=running enabled=yes
  tags:
    - test
